"""Add age, bjj_belt_rank, weight fields to players and update weight_classes to use lbs

Revision ID: 114ffbab871b
Revises: bebbdbed31be
Create Date: 2025-11-09 19:24:24.501199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114ffbab871b'
down_revision: Union[str, None] = 'bebbdbed31be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('bjj_belt_rank', sa.String(), nullable=True))
    op.add_column('players', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('weight_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'players', 'weight_classes', ['weight_class_id'], ['id'])
    op.add_column('weight_classes', sa.Column('min_lbs', sa.Float(), nullable=True))
    op.add_column('weight_classes', sa.Column('max_lbs', sa.Float(), nullable=True))
    op.drop_column('weight_classes', 'min_kg')
    op.drop_column('weight_classes', 'max_kg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weight_classes', sa.Column('max_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('weight_classes', sa.Column('min_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('weight_classes', 'max_lbs')
    op.drop_column('weight_classes', 'min_lbs')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'weight_class_id')
    op.drop_column('players', 'weight')
    op.drop_column('players', 'bjj_belt_rank')
    op.drop_column('players', 'age')
    # ### end Alembic commands ###
