"""add_tournament_engine_schema

Revision ID: 781120c01863
Revises: 062dcc342f21
Create Date: 2025-11-11 17:44:35.188313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781120c01863'
down_revision: Union[str, None] = '062dcc342f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types that will be used by new tables (tournamentformat and roundstatus)
    # These will be created automatically when creating the tables

    op.create_table('bracket_formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('weight_class_id', sa.Integer(), nullable=True),
    sa.Column('format_type', sa.Enum('SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'SWISS', 'ROUND_ROBIN', 'GUARANTEED_MATCHES', name='tournamentformat'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('min_rest_minutes', sa.Integer(), nullable=False),
    sa.Column('max_matches_per_session', sa.Integer(), nullable=True),
    sa.Column('auto_generate', sa.Boolean(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['weight_class_id'], ['weight_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bracket_formats_event_id'), 'bracket_formats', ['event_id'], unique=False)
    op.create_index(op.f('ix_bracket_formats_id'), 'bracket_formats', ['id'], unique=False)
    op.create_index(op.f('ix_bracket_formats_weight_class_id'), 'bracket_formats', ['weight_class_id'], unique=False)
    op.create_table('bracket_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bracket_format_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('round_name', sa.String(), nullable=True),
    sa.Column('bracket_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='roundstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('round_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bracket_format_id'], ['bracket_formats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bracket_rounds_bracket_format_id'), 'bracket_rounds', ['bracket_format_id'], unique=False)
    op.create_index(op.f('ix_bracket_rounds_id'), 'bracket_rounds', ['id'], unique=False)

    # Create matchstatus enum for the matches table columns
    sa.Enum('PENDING', 'READY', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='matchstatus').create(op.get_bind(), checkfirst=True)

    op.add_column('matches', sa.Column('bracket_round_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('match_status', sa.Enum('PENDING', 'READY', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='matchstatus'), nullable=True))
    op.add_column('matches', sa.Column('match_number', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('depends_on_match_a', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('depends_on_match_b', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('requires_winner_a', sa.Boolean(), nullable=True))
    op.add_column('matches', sa.Column('requires_winner_b', sa.Boolean(), nullable=True))
    op.add_column('matches', sa.Column('scheduled_time', sa.DateTime(), nullable=True))
    op.add_column('matches', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('matches', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('matches', 'a_player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matches', 'b_player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_matches_bracket_round_id'), 'matches', ['bracket_round_id'], unique=False)
    op.create_foreign_key(None, 'matches', 'bracket_rounds', ['bracket_round_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'matches', ['depends_on_match_a'], ['id'])
    op.create_foreign_key(None, 'matches', 'matches', ['depends_on_match_b'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_index(op.f('ix_matches_bracket_round_id'), table_name='matches')
    op.alter_column('matches', 'b_player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matches', 'a_player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('matches', 'completed_at')
    op.drop_column('matches', 'started_at')
    op.drop_column('matches', 'scheduled_time')
    op.drop_column('matches', 'requires_winner_b')
    op.drop_column('matches', 'requires_winner_a')
    op.drop_column('matches', 'depends_on_match_b')
    op.drop_column('matches', 'depends_on_match_a')
    op.drop_column('matches', 'match_number')
    op.drop_column('matches', 'match_status')
    op.drop_column('matches', 'bracket_round_id')
    op.drop_index(op.f('ix_bracket_rounds_id'), table_name='bracket_rounds')
    op.drop_index(op.f('ix_bracket_rounds_bracket_format_id'), table_name='bracket_rounds')
    op.drop_table('bracket_rounds')
    op.drop_index(op.f('ix_bracket_formats_weight_class_id'), table_name='bracket_formats')
    op.drop_index(op.f('ix_bracket_formats_id'), table_name='bracket_formats')
    op.drop_index(op.f('ix_bracket_formats_event_id'), table_name='bracket_formats')
    op.drop_table('bracket_formats')

    # Drop enum types
    sa.Enum(name='matchstatus').drop(op.get_bind())
    sa.Enum(name='roundstatus').drop(op.get_bind())
    sa.Enum(name='tournamentformat').drop(op.get_bind())
    # ### end Alembic commands ###
