"""Add event timing fields

Revision ID: 790e5a094394
Revises: 112b01734ba2
Create Date: 2025-11-10 01:57:04.669515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790e5a094394'
down_revision: Union[str, None] = '112b01734ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('fighter_arrival_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('event_start_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_start_time')
    op.drop_column('events', 'fighter_arrival_time')
    # ### end Alembic commands ###
