"""Add weight class specific ELO ratings

Revision ID: 800bb7707cc7
Revises: 790e5a094394
Create Date: 2025-11-10 14:51:05.636405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800bb7707cc7'
down_revision: Union[str, None] = '790e5a094394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('elo_lightweight', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('elo_middleweight', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('elo_heavyweight', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('initial_elo_lightweight', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('initial_elo_middleweight', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('initial_elo_heavyweight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'initial_elo_heavyweight')
    op.drop_column('players', 'initial_elo_middleweight')
    op.drop_column('players', 'initial_elo_lightweight')
    op.drop_column('players', 'elo_heavyweight')
    op.drop_column('players', 'elo_middleweight')
    op.drop_column('players', 'elo_lightweight')
    # ### end Alembic commands ###
