"""Add Rankade sync tracking fields to matches

Revision ID: 83edfcd82979
Revises: 114ffbab871b
Create Date: 2025-11-09 19:30:32.245060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83edfcd82979'
down_revision: Union[str, None] = '114ffbab871b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('synced_to_rankade', sa.Boolean(), nullable=True))
    op.add_column('matches', sa.Column('rankade_sync_error', sa.Text(), nullable=True))
    op.add_column('matches', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_matches_rankade_match_id'), 'matches', ['rankade_match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_rankade_match_id'), table_name='matches')
    op.drop_column('matches', 'updated_at')
    op.drop_column('matches', 'rankade_sync_error')
    op.drop_column('matches', 'synced_to_rankade')
    # ### end Alembic commands ###
