"""Update weigh_ins to use lbs and add weighed_at

Revision ID: c4b4399033aa
Revises: 83edfcd82979
Create Date: 2025-11-09 19:39:49.812281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b4399033aa'
down_revision: Union[str, None] = '83edfcd82979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weigh_ins', sa.Column('weight', sa.Float(), nullable=False))
    op.add_column('weigh_ins', sa.Column('weighed_at', sa.DateTime(), nullable=True))
    op.drop_column('weigh_ins', 'weight_kg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weigh_ins', sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('weigh_ins', 'weighed_at')
    op.drop_column('weigh_ins', 'weight')
    # ### end Alembic commands ###
